sudo: false

language: node_js

node_js:
  - '0.12'

branches:
  only:
    - master
    - travis-ci

# Not using `npm install --dev` because it is recursive. It will pull in the all
# development dependencies for CoffeeScript. Way too much spew in the Travis CI
# build output.

before_install:
  - npm install
  - npm install istanbul coveralls

env:
  global:
  - secure: "UeSetdv5QV8oebw5Y/SoekVQofdfCYhnJaxs6qdY7ebeUhf721O4XcGpbpOU7/d9n+SHecBXZ7bcXjvVmP+K1P07U17Fc/Z72Ur1pP2g3vs4ZxYYMIgYRZ+sR0ywTOEEszsMXRuw8wr+56VbxpUKHIBsDCl2WPARo/7NFS1OWhOMtBFQZf1+bYkMEtD9Aw5BSyLWOBC5vBtIoBY6dif63ZLEinUx6AjfhSek0il3c+mfn9H7lYitrTLrgbVSy2CtUJv0K+hGZpb1tn0GbyN7t+o2qCPUTTIfxcNTdr+3Vkq1vnQVCMXQ2/10gjNyWPMKd7XnMU7SjN6L6ihtdIgj3Vs8y0icDal6G20+910b7xhD+y5yHodPGBNFc2L2RN6EEpSDTmXf1Jea4qZtrLNMmbcM3Sh6AuRb83lL0nzjomW/Oaw6A8ES4qZUZSXoSg5tEd+/rrXaRN5zzk/SMt9YskEYAAkInEnwRfr7OnOnoQvu3uid91SNjl7q/ZGqMLS4s00UsCPEsjb/J1hMfhTWAZyJC1OjetnUu1ODqA2okpjxzH9VdlL7kzCMTi/gmBK6mmQhfwmT2an2K0jX68+SApqDr14syDViwO5XZebhLTYfAKpKjDHX/PtDsrH/gec4b7ZIq511nVim0fcx6DP6vT91NstETsNnyrVXUbISLaE="
